In [ ]:
ENSEMBLE LEARNING

* Ensemble learning helps improve machine learning results by combining several models. 
This approach allows the production of better predictive performance compared to a single model.
* Random forest is a Supervised Machine Learning Algorithm that is used widely in Classification and Regression problems.
It builds decision trees on different samples and takes their majority vote for classification and average in case of regression.

    Two types:
1)    Bagging: 
        * Random Forest
            Equally parellely divide into several groups or models and train all the models which results in an outcome of predicting which one is which.
2)    Boosting

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
# from sklearn.datasets import load_iris
# iris=load_iris()
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.svm import SVR

In [3]:
mr=pd.read_csv('drug200.csv')
mr

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [5]:
mr.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [7]:
mr.tail()

     Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [11]:
mr.shape

(200, 6)

In [13]:
mr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [15]:
mr.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [17]:
mr.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [19]:
mr

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [21]:
le=LabelEncoder()
msex=le.fit_transform(mr['Sex'])
mbp=le.fit_transform(mr['BP'])
mchol=le.fit_transform(mr['Cholesterol'])
mna=le.fit_transform(mr['Na_to_K'])
mdrug=le.fit_transform(mr['Drug'])
mr.Sex=msex
mr.BP=mbp
mr.Cholesterol=mchol
mr.Na_to_K=mna
mr.Drug=mdrug

In [23]:
mr

     Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0      167     0
1     47    1   1            0       89     3
2     47    1   1            0       43     3
3     28    0   2            0       10     4
4     61    0   1            0      133     0
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0       69     3
196   16    1   1            0       75     3
197   52    1   2            0       36     4
198   23    1   2            1      102     4
199   40    0   1            1       66     4

[200 rows x 6 columns]

In [25]:
mr.corr

<bound method DataFrame.corr of      Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0      167     0
1     47    1   1            0       89     3
2     47    1   1            0       43     3
3     28    0   2            0       10     4
4     61    0   1            0      133     0
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0       69     3
196   16    1   1            0       75     3
197   52    1   2            0       36     4
198   23    1   2            1      102     4
199   40    0   1            1       66     4

[200 rows x 6 columns]>

In [27]:
x=mr.drop(['Sex','Drug'],axis='columns')
print(type(x))

<class 'pandas.core.frame.DataFrame'>

In [29]:
x

     Age  BP  Cholesterol  Na_to_K
0     23   0            0      167
1     47   1            0       89
2     47   1            0       43
3     28   2            0       10
4     61   1            0      133
..   ...  ..          ...      ...
195   56   1            0       69
196   16   1            0       75
197   52   2            0       36
198   23   2            1      102
199   40   1            1       66

[200 rows x 4 columns]

In [31]:
y=mr['Drug']
print(type(y))

<class 'pandas.core.series.Series'>

In [33]:
y

0      0
1      3
2      3
3      4
4      0
      ..
195    3
196    3
197    4
198    4
199    4
Name: Drug, Length: 200, dtype: int32

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [39]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=60)
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=60)

In [47]:
model3=RandomForestClassifier(n_estimators=10)
model3.fit(x_train,y_train)
model3.score(x_test,y_test)

0.95

In [49]:
model1=RandomForestClassifier(n_estimators=40)
model1.fit(x_train,y_train)
model1.score(x_test,y_test)

0.9666666666666667

In [51]:
model2=RandomForestClassifier(n_estimators=30)
model2.fit(x_train,y_train)
model2.score(x_test,y_test)

0.9333333333333333

In [53]:
model.score(x_test,y_test)

0.95

In [55]:
model.predict(x_test)

array([4, 0, 4, 3, 0, 4, 4, 0, 0, 0, 4, 3, 0, 0, 1, 1, 4, 4, 2, 0, 4, 4,
       4, 0, 2, 4, 4, 0, 4, 4, 3, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 4,
       2, 0, 4, 4, 0, 1, 0, 0, 0, 0, 0, 0, 4, 4, 4, 1])

In [57]:
model.predict_proba(x_test)

array([[0.        , 0.        , 0.03333333, 0.06666667, 0.9       ],
       [0.96666667, 0.        , 0.        , 0.        , 0.03333333],
       [0.06666667, 0.01666667, 0.01666667, 0.01666667, 0.88333333],
       [0.        , 0.        , 0.        , 0.88333333, 0.11666667],
       [0.98333333, 0.01666667, 0.        , 0.        , 0.        ],
       [0.08333333, 0.        , 0.        , 0.03333333, 0.88333333],
       [0.        , 0.        , 0.        , 0.01666667, 0.98333333],
       [0.98333333, 0.        , 0.        , 0.01666667, 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.03333333, 0.96666667],
       [0.        , 0.        , 0.        , 0.78333333, 0.21666667],
       [0.96666667, 0.03333333, 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.03333333, 0.8       , 0.11666667, 0.01666667, 0.03333333],
       [0.        , 0.96666667, 0.03333333, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ],
       [0.01666667, 0.        , 0.        , 0.        , 0.98333333],
       [0.05      , 0.23333333, 0.63333333, 0.06666667, 0.01666667],
       [0.96666667, 0.03333333, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.01666667, 0.05      , 0.93333333],
       [0.01666667, 0.        , 0.05      , 0.06666667, 0.86666667],
       [0.05      , 0.01666667, 0.        , 0.03333333, 0.9       ],
       [0.43333333, 0.01666667, 0.03333333, 0.36666667, 0.15      ],
       [0.08333333, 0.03333333, 0.8       , 0.        , 0.08333333],
       [0.06666667, 0.        , 0.        , 0.03333333, 0.9       ],
       [0.        , 0.        , 0.        , 0.03333333, 0.96666667],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.05      , 0.        , 0.01666667, 0.4       , 0.53333333],
       [0.01666667, 0.01666667, 0.        , 0.        , 0.96666667],
       [0.05      , 0.        , 0.05      , 0.6       , 0.3       ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.93333333, 0.06666667, 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.88333333, 0.1       , 0.01666667, 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.03333333, 0.91666667, 0.05      , 0.        , 0.        ],
       [0.98333333, 0.        , 0.        , 0.        , 0.01666667],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.98333333, 0.        , 0.        , 0.        , 0.01666667],
       [0.05      , 0.06666667, 0.8       , 0.        , 0.08333333],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.05      , 0.        , 0.        , 0.1       , 0.85      ],
       [0.03333333, 0.08333333, 0.85      , 0.        , 0.03333333],
       [0.96666667, 0.03333333, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ],
       [0.01666667, 0.01666667, 0.        , 0.1       , 0.86666667],
       [0.95      , 0.        , 0.        , 0.        , 0.05      ],
       [0.01666667, 0.73333333, 0.21666667, 0.03333333, 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.96666667, 0.        , 0.03333333, 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.98333333, 0.        , 0.        , 0.        , 0.01666667],
       [0.96666667, 0.        , 0.        , 0.        , 0.03333333],
       [0.05      , 0.01666667, 0.03333333, 0.06666667, 0.83333333],
       [0.        , 0.        , 0.        , 0.05      , 0.95      ],
       [0.        , 0.        , 0.        , 0.01666667, 0.98333333],
       [0.        , 0.81666667, 0.16666667, 0.01666667, 0.        ]])